### ISSUE TITLE
Recursive function in setup script not working: 'scandir' is not defined

### ISSUE THREAD

**Issue by abrekhov** [PySlurm/pyslurm#185]
#### Details

* Slurm Version: 19.05.3
* Python Version: 3.6
* Cython Version: 0.29.23
* PySlurm Branch: 19.05
* Linux Distribution: CentOS

#### Issue
```
[root@head1.hpc3 pyslurm]# python  setup.py build
INFO:
INFO: Building PySlurm (19.05.0.0)
INFO: ------------------------------
INFO:
INFO: Cython version 0.29.22 installed
INFO:
INFO: Clean - checking for objects to clean
INFO: Clean - removing pyslurm/bluegene.pxi
INFO: Clean - completed
INFO: Build - Found Slurm header in /usr/include
INFO: Build - Detected Slurm version - 0x130503 (19.05.03)
INFO: Build - Found Slurm shared library in /usr/lib64
INFO: Build - Generating pyslurm/bluegene.pxi file
Traceback (most recent call last):
  File "setup.py", line 344, in <module>
    Pyslurm().setup_package()
  File "setup.py", line 297, in setup_package
    extNames = self.scandir("pyslurm/")
  File "setup.py", line 91, in scandir
    scandir(path, files)
NameError: global name 'scandir' is not defined
```
Very strange thing...

**Comment by tazend** [comment]
Closing this, since `setup.py` has been reworked some time ago and doesn't use `scandir` anymore.
