### ISSUE TITLE
pyslurm throw KeyError 5039  when statistics().get() called

### ISSUE THREAD

**Issue by sterni1971** [PySlurm/pyslurm#284]
#### Details

* Slurm Version: 22.05
* Python Version: 3.6.8
* Cython Version: 0.28.1
* PySlurm Branch:  22.05.0-1
* Linux Distribution: Alma 8

Suddenly, my monitor script died after running without any issues for the last weeks.
Steps to reproduce:

>>> import pyslurm
>>> sdiag = pyslurm.statistics()
>>> sdiag.get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm/pyslurm.pyx", line 4497, in pyslurm.pyslurm.statistics.get
  File "pyslurm/pyslurm.pyx", line 4556, in pyslurm.pyslurm.statistics.get
  File "pyslurm/pyslurm.pyx", line 4837, in pyslurm.pyslurm.statistics.__rpc_num2string
KeyError: 5039

Seems to be similar to https://github.com/PySlurm/pyslurm/issues/101 :-)

**Comment by sterni1971** [comment]
It should be fixed here https://github.com/PySlurm/pyslurm/commit/61d4740c4c2e812e4983ab9558d1d23060b93c7f

**Comment by tazend** [comment]
Hi @sterni1971 

The commit you mentioned is already included in the latest release for 22.05. You can use the [22.05](https://github.com/PySlurm/pyslurm/tree/22.05) branch :)
