### ISSUE TITLE
Python3 error in job().get()

### ISSUE THREAD

**Issue by hillenbrkl** [PySlurm/pyslurm#72]
I have compiled pyslurm for python3.4 on EL7. When I call jobs = pyslurm.job().get() I get the following error:

Traceback (most recent call last):
  File "./slurm2json", line 187, in <module>
    jobs = pyslurm.job().get()
  File "pyslurm/pyslurm.pyx", line 1934, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:27121)
  File "pyslurm/pyslurm.pyx", line 1950, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:27024)
  File "pyslurm/pyslurm.pyx", line 2147, in pyslurm.pyslurm.job.get_job_ptr (pyslurm/pyslurm.c:28904)
TypeError: 'str' does not support the buffer interface

When I modify pyslurm.pyx line 2147 to 

Job_dict[u'state_reason'] = self._record.state_desc.decode().replace(" ", "_")

it works.

Is python3 support not yet completely tested?

Markus

**Comment by giovtorres** [comment]
Hi Markus,

Python 3 is not yet fully supported at this time.  We are aiming to have much improved support for Python 3 by the next Slurm release (17.02).

Giovanni
