### ISSUE TITLE
Update for Slurm 17.11.1

### ISSUE THREAD

**Issue by wilshire461** [PySlurm/pyslurm#98]
I ran into some issues building pyslurm for slurm 17.11.1 after adjusting the max version hex in setup.py I got the following

```
Info: 
Info: Building PySlurm (17.02.0)
Info: ------------------------------
Info: 
Info: Cython version 0.25.2 installed
Info: Clean - checking for objects to clean
Info: Clean - completed
Info: Build - Detected Slurm include file version - 0x110b01 (17.11.01)
Info: Build - Found Slurm shared library in /usr/lib64
Info: Build - Writing Slurm version to pyslurm/slurm_version.pxi
Info: Build - Generating pyslurm/bluegene.pxi file
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pyslurm
copying pyslurm/__init__.py -> build/lib.linux-x86_64-2.7/pyslurm
running build_ext
cythoning pyslurm/pyslurm.pyx to pyslurm/pyslurm.c
building 'pyslurm.pyslurm' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pyslurm
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include -I. -I/usr/include/python2.7 -c pyslurm/pyslurm.c -o build/temp.linux-x86_64-2.7/pyslurm/pyslurm.o
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_6config___get’:
pyslurm/pyslurm.c:11530:86: error: ‘slurm_ctl_conf_t’ has no member named ‘acct_gather_infiniband_type’
     __pyx_t_1 = __pyx_f_7pyslurm_5slurm_stringOrNone(__pyx_v_self->__pyx___Config_ptr->acct_gather_infiniband_type, __pyx_kp_s_); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 510, __pyx_L1_error)
                                                                                      ^
pyslurm/pyslurm.c:11962:75: error: ‘slurm_ctl_conf_t’ has no member named ‘group_info’
     __pyx_t_1 = __Pyx_PyInt_From_uint16_t(__pyx_v_self->__pyx___Config_ptr->group_info); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 544, __pyx_L1_error)
                                                                           ^
pyslurm/pyslurm.c:13758:75: error: ‘slurm_ctl_conf_t’ has no member named ‘z_16’
     __pyx_t_1 = __Pyx_PyInt_From_uint16_t(__pyx_v_self->__pyx___Config_ptr->z_16); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 686, __pyx_L1_error)
                                                                           ^
pyslurm/pyslurm.c:13770:75: error: ‘slurm_ctl_conf_t’ has no member named ‘z_32’
     __pyx_t_1 = __Pyx_PyInt_From_uint32_t(__pyx_v_self->__pyx___Config_ptr->z_32); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 687, __pyx_L1_error)
                                                                           ^
pyslurm/pyslurm.c:13782:86: error: ‘slurm_ctl_conf_t’ has no member named ‘z_char’
     __pyx_t_1 = __pyx_f_7pyslurm_5slurm_stringOrNone(__pyx_v_self->__pyx___Config_ptr->z_char, __pyx_kp_s_); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 688, __pyx_L1_error)
                                                                                      ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_3job_get_job_ptr’:
pyslurm/pyslurm.c:27996:75: error: ‘slurm_job_info_t’ has no member named ‘batch_script’
     __pyx_t_1 = __pyx_f_7pyslurm_5slurm_stringOrNone(__pyx_v_self->_record->batch_script, __pyx_kp_s_); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 2030, __pyx_L1_error)
                                                                           ^
pyslurm/pyslurm.c:28513:75: error: ‘slurm_job_info_t’ has no member named ‘fed_siblings_str’
     __pyx_t_6 = __pyx_f_7pyslurm_5slurm_stringOrNone(__pyx_v_self->_record->fed_siblings_str, __pyx_kp_s_); if (unlikely(!__pyx_t_6)) __PYX_ERR(0, 2082, __pyx_L1_error)
                                                                           ^
error: command 'gcc' failed with exit status 1
```

**Comment by giovtorres** [comment]
Hi @wilshire461, it looks like your cluster is 17.11.01 but you're on the 17.02.0 PySlurm branch.  Pull in any updates to the repo and switch to the 17.11.0 branch (or master, as they are both even at this point) and try again.

```
Info: Building PySlurm (17.02.0)
...
Info: Build - Detected Slurm include file version - 0x110b01 (17.11.01)
```

Thanks.

**Comment by wilshire461** [comment]
Thanks @giovtorres, I have however run into some other issues.  When trying to use a script that queried slurm stats using pyslurm.statistics().get() I get the following errors.

`[root@slurm6 ~]# python
Python 2.7.5 (default, Aug  2 2016, 04:20:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyslurm
>>> pyslurm.statistics().get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm/pyslurm.pyx", line 4301, in pyslurm.pyslurm.statistics.get
  File "pyslurm/pyslurm.pyx", line 4356, in pyslurm.pyslurm.statistics.get
  File "pyslurm/pyslurm.pyx", line 4611, in pyslurm.pyslurm.statistics.__rpc_num2string
KeyError: 2049
>>> `

**Comment by giovtorres** [comment]
Could you tell me which version of Slurm, branch of PySlurm and OS version?

**Comment by wilshire461** [comment]
Red Hat Enterprise Linux Server release 7.2 (Maipo)
slurm 17.11.1-2
built off the master branch

**Comment by giovtorres** [comment]
Ah, looks like I'm missed some enum members: https://github.com/SchedMD/slurm/blob/75f0789d0689edca1b6e800ce9724004f1f375b7/src/common/slurm_protocol_defs.h#L264-L271

I'll add them in a bit and push.  Thanks for pointing this out!

**Comment by giovtorres** [comment]
I added the missing members in 1940541.  Give it a try now.

**Comment by wilshire461** [comment]
That fixed the earlier enum members, but I think we are now missing some job_pack enums
```
# python
Python 2.7.5 (default, Aug  2 2016, 04:20:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyslurm
>>> pyslurm.statistics().get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm/pyslurm.pyx", line 4301, in pyslurm.pyslurm.statistics.get
  File "pyslurm/pyslurm.pyx", line 4356, in pyslurm.pyslurm.statistics.get
  File "pyslurm/pyslurm.pyx", line 4619, in pyslurm.pyslurm.statistics.__rpc_num2string
KeyError: 4027
```
https://github.com/SchedMD/slurm/blob/75f0789d0689edca1b6e800ce9724004f1f375b7/src/common/slurm_protocol_defs.h#L313-L316

**Comment by giovtorres** [comment]
Ok, I ran `git diff slurm-17-02-9-1 slurm-17-11-1-2 src/common/slurm_protocol_defs.h` to catch anything I missed since upgrading pyslurm support from slurm 17.02 to 17.11.  This file is not directly part of the API and must have been why I missed it.  I'll add it to the list of files to check during updates.  

Try again now.  

Thanks again.

**Comment by wilshire461** [comment]
Great success!

Thank you for the quick turnaround, and of course all the work that has gone into this great module.
